/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: shinymagic (https://sketchfab.com/shinymagic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/looking-glass-hologram-concept-3-512957326d0c4e9289e1a62dd9e1575c
Title: Looking Glass Hologram Concept 3
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Glass(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/glasssssss.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="d9e1ccbfe3e14b649a2769d83692851afbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="Line018"
                  position={[0.02, 0.064, 0.483]}
                  rotation={[0, 0, -2.967]}
                  scale={0.001}>
                  <mesh
                    name="Line018_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line018_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line014"
                  position={[0.079, 0.098, 0.483]}
                  rotation={[0, 0, -2.269]}
                  scale={0.001}>
                  <mesh
                    name="Line014_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line014_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line015"
                  position={[0.067, 0.085, 0.483]}
                  rotation={[0, 0, -2.443]}
                  scale={0.001}>
                  <mesh
                    name="Line015_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line015_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line016"
                  position={[0.052, 0.075, 0.483]}
                  rotation={[0, 0, -2.618]}
                  scale={0.001}>
                  <mesh
                    name="Line016_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line016_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line017"
                  position={[0.036, 0.068, 0.483]}
                  rotation={[0, 0, -2.793]}
                  scale={0.001}>
                  <mesh
                    name="Line017_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line017_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line019"
                  position={[0.002, 0.062, 0.483]}
                  rotation={[0, 0, -Math.PI]}
                  scale={0.001}>
                  <mesh
                    name="Line019_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line019_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line020"
                  position={[-0.015, 0.064, 0.483]}
                  rotation={[0, 0, 2.967]}
                  scale={0.001}>
                  <mesh
                    name="Line020_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line020_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line021"
                  position={[-0.032, 0.068, 0.483]}
                  rotation={[0, 0, 2.793]}
                  scale={0.001}>
                  <mesh
                    name="Line021_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line021_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line022"
                  position={[-0.048, 0.075, 0.483]}
                  rotation={[0, 0, 2.618]}
                  scale={0.001}>
                  <mesh
                    name="Line022_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line022_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line023"
                  position={[-0.062, 0.085, 0.483]}
                  rotation={[0, 0, 2.443]}
                  scale={0.001}>
                  <mesh
                    name="Line023_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line023_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line024"
                  position={[-0.074, 0.098, 0.483]}
                  rotation={[0, 0, 2.269]}
                  scale={0.001}>
                  <mesh
                    name="Line024_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line024_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line025"
                  position={[-0.084, 0.112, 0.483]}
                  rotation={[0, 0, 2.094]}
                  scale={0.001}>
                  <mesh
                    name="Line025_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line025_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line026"
                  position={[-0.092, 0.128, 0.483]}
                  rotation={[0, 0, 1.92]}
                  scale={0.001}>
                  <mesh
                    name="Line026_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line026_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line027"
                  position={[-0.096, 0.145, 0.483]}
                  rotation={[0, 0, 1.745]}
                  scale={0.001}>
                  <mesh
                    name="Line027_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line027_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line028"
                  position={[-0.098, 0.162, 0.483]}
                  rotation={[0, 0, Math.PI / 2]}
                  scale={0.001}>
                  <mesh
                    name="Line028_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line028_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line029"
                  position={[-0.096, 0.179, 0.483]}
                  rotation={[0, 0, 1.396]}
                  scale={0.001}>
                  <mesh
                    name="Line029_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line029_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line030"
                  position={[-0.092, 0.196, 0.483]}
                  rotation={[0, 0, 1.222]}
                  scale={0.001}>
                  <mesh
                    name="Line030_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line030_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line031"
                  position={[-0.084, 0.212, 0.483]}
                  rotation={[0, 0, Math.PI / 3]}
                  scale={0.001}>
                  <mesh
                    name="Line031_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line031_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line036"
                  position={[-0.015, 0.261, 0.483]}
                  rotation={[0, 0, 0.175]}
                  scale={0.001}>
                  <mesh
                    name="Line036_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line036_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line032"
                  position={[-0.074, 0.226, 0.483]}
                  rotation={[0, 0, 0.873]}
                  scale={0.001}>
                  <mesh
                    name="Line032_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line032_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line033"
                  position={[-0.062, 0.239, 0.483]}
                  rotation={[0, 0, 0.698]}
                  scale={0.001}>
                  <mesh
                    name="Line033_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line033_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line034"
                  position={[-0.048, 0.249, 0.483]}
                  rotation={[0, 0, Math.PI / 6]}
                  scale={0.001}>
                  <mesh
                    name="Line034_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line034_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line035"
                  position={[-0.032, 0.256, 0.483]}
                  rotation={[0, 0, Math.PI / 9]}
                  scale={0.001}>
                  <mesh
                    name="Line035_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line035_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line013"
                  position={[0.089, 0.112, 0.483]}
                  rotation={[0, 0, -2.094]}
                  scale={0.001}>
                  <mesh
                    name="Line013_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line013_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line012"
                  position={[0.096, 0.128, 0.483]}
                  rotation={[0, 0, -1.92]}
                  scale={0.001}>
                  <mesh
                    name="Line012_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line012_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line011"
                  position={[0.101, 0.145, 0.483]}
                  rotation={[0, 0, -1.745]}
                  scale={0.001}>
                  <mesh
                    name="Line011_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line011_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line010"
                  position={[0.102, 0.162, 0.483]}
                  rotation={[0, 0, -Math.PI / 2]}
                  scale={0.001}>
                  <mesh
                    name="Line010_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line010_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line009"
                  position={[0.101, 0.179, 0.483]}
                  rotation={[0, 0, -1.396]}
                  scale={0.001}>
                  <mesh
                    name="Line009_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line009_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line008"
                  position={[0.096, 0.196, 0.483]}
                  rotation={[0, 0, -1.222]}
                  scale={0.001}>
                  <mesh
                    name="Line008_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line008_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line037"
                  position={[0.089, 0.212, 0.483]}
                  rotation={[0, 0, -Math.PI / 3]}
                  scale={0.001}>
                  <mesh
                    name="Line037_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line037_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line038"
                  position={[0.079, 0.226, 0.483]}
                  rotation={[0, 0, -0.873]}
                  scale={0.001}>
                  <mesh
                    name="Line038_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line038_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line039"
                  position={[0.067, 0.239, 0.483]}
                  rotation={[0, 0, -0.698]}
                  scale={0.001}>
                  <mesh
                    name="Line039_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line039_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line040"
                  position={[0.052, 0.249, 0.483]}
                  rotation={[0, 0, -Math.PI / 6]}
                  scale={0.001}>
                  <mesh
                    name="Line040_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line040_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line041"
                  position={[0.036, 0.256, 0.483]}
                  rotation={[0, 0, -Math.PI / 9]}
                  scale={0.001}>
                  <mesh
                    name="Line041_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line041_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Line042"
                  position={[0.02, 0.261, 0.483]}
                  rotation={[0, 0, -0.175]}
                  scale={0.001}>
                  <mesh
                    name="Line042_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line042_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group name="Line043" position={[0.002, 0.262, 0.483]} scale={0.001}>
                  <mesh
                    name="Line043_01_-_Default_0"
                    castShadow
                    receiveShadow
                    geometry={nodes['Line043_01_-_Default_0'].geometry}
                    material={materials['01_-_Default']}
                  />
                </group>
                <group
                  name="Circle002"
                  position={[0.002, 0.162, 0.483]}
                  rotation={[0.002, 0, 0]}
                  scale={0.002}>
                  <mesh
                    name="Circle002_bright_blue_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.Circle002_bright_blue_0.geometry}
                    material={materials.bright_blue}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/glasssssss.glb')


